### ISSUE TITLE
Discussion: Rename metadata to common

### ISSUE THREAD

**Issue by Insti** [exercism/x-api#129]
While looking into https://github.com/exercism/x-common/issues/269 and what needs to change in x-api  if we move the x-common files it was not really clear that the `metadata` path was a link to the `x-common` repository. (See also #127 about documenting this.)

I propose that we rename the `metadata` directory to `common` to match the current usage and repository naming.

**Comment by Insti** [comment]
Or move it to 'tracks/common' and get it out of the root directory completely.

**Comment by kytrinyx** [comment]
> I propose that we rename the metadata directory to common to match the current usage and repository naming.

I think that makes sense.

I don't really want it in tracks because it's not a track. I can see how it would make sense with tracks/common... sort of :) But it would also potentially be harder to scan the `tracks/` directory and know what you're doing, and we'd have to have special logic to _not_ treat it as a track.
