### ISSUE TITLE
Provide categories to tracks

### ISSUE THREAD

**Issue by alexcameron89** [exercism/x-api#135]
This is from a discussion on the [Exercism website repository](https://github.com/exercism/exercism.io/pull/3086):

> We really should figure out what the right approach is in terms of data and fix this at the source of truth: https://github.com/exercism/x-api

@kytrinyx would the best approach for sectioning out tracks by category be to add category paths to the tracks route? Example: `get '/tracks/active'`, etc.

**Comment by kytrinyx** [comment]
The categorization that we've been using has been:

- active ("active" flag `true` in the config.json)
- upcoming ("active" flag `false`, and there is at least one exercise)
- planned ("active" flag `false`, and no exercises)

Perhaps we could add a new field `status` to the track which is one of ["active", "upcoming", "planned"]. Let's not touch the existing fields yet, in case they're used in ways that we have forgotten. Then the website can start using the status field instead of the active/inactive fields.

**Comment by kytrinyx** [comment]
No, we no longer need this, as we've solved it in the `Trackler` gem. Thanks for pinging on the issue!
