### ISSUE TITLE
Internal Server Error when fetching Go track

### ISSUE THREAD

**Issue by jcbwlkr** [exercism/x-api#63]
When I try to fetch the Go track I get an internal server error. I can fetch other tracks and friends of mine can fetch the Go track. Command output:

    ~/exercism ᐳ exercism fetch go
    2015/07/06 12:33:46 an internal server error was received.
    Please file a bug report with the contents of 'exercism debug' at: https://github.com/exercism/x-api/issues 
    ~/exercism 1 ᐳ exercism debug

    **** Debug Information ****
    Exercism CLI Version: 2.2.0
    Exercism CLI Latest Release: 2.2.0
    OS/Architecture: darwin/amd64
    Build OS/Architecture darwin/amd64
    Home Dir: /Users/jwalker
    Config file: /Users/jwalker/.exercism.json
    API Key: XXXXXXXXXXXXXXXXXXXX
    API: http://exercism.io [connected]
    XAPI: http://x.exercism.io [connected]
    Exercises Directory: /Users/jwalker/exercism

Other (potentially misleading) information: before this came up I had just submitted the `secret-handshake` problem. Looking at the [Go track config](https://github.com/exercism/xgo/blob/master/config.json) it looks like I somehow skipped the `error-handling` problem. Maybe this is relevant?

**Comment by kytrinyx** [comment]
Oooh. The error handling problem is new as of yesterday. I'm in a meeting but will look into this as soon as I'm out.

**Comment by kytrinyx** [comment]
OK, it turns out that the API is not dealing with the binary data in the file. Up until now all the files have been utf-8 encoded, and it hasn't been necessary to handle anything more complex. We're going to need to base64 encode the files, I think; but this will require a change to the CLI as well.

For now I've simply redeployed the API without the error-handling problem.

I'm leaving this issue open until I can create a new issue in the api repo to deal with it (I'm traveling this week).

**Comment by kytrinyx** [comment]
I put in a workaround for this so that the go track is fetchable. See https://github.com/exercism/x-api/issues/64
